import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/HomeComponents/NavBar";
import Footer from "@/components/HomeComponents/Footer";
import ChatBox from "@/components/ChatBox";
import AuthContext from "@/utils/AuthContext";
import useAuth from "@/utils/useAuth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { user, loading, error, logout } = useAuth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContext.Provider value={{user,logout}}>
          <NavBar />
          {children}
          <ChatBox/>
          <Footer />
        </AuthContext.Provider>
      </body>
    </html>
  );
}
